[package]
name = "resource_proof"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description ="A 'proof' of bandwidth, cpu and storage for nodes in a decentralised network"
repository = "https://github.com/dirvine/resource_proof"
license = "GPL-3.0"
version = "0.1.0"
readme = "README.md"

[dependencies]
clippy = {version = "~0.0.86", optional = true}
itertools = "0.4.18"
maidsafe_utilities = "~0.9.0"
rayon = "~0.4.0"
rust_sodium = "~0.1.1"
rustc-serialize = "~0.3.19"
tiny-keccak = "~1.1.1"

[dev-dependencies]
rand = "~0.3.14"
tempdir = "~0.3.5"
unwrap = "~1.1.0"
