[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "A 'proof' of bandwidth, cpu and storage for nodes in a decentralised network"
license = "GPL-3.0"
name = "resource_proof"
readme = "README.md"
repository = "https://github.com/dirvine/resource_proof"
version = "0.2.1-pre"

[dependencies]
clap = "~2.14.0"
termion = "~1.1.1"
tiny-keccak = "~1.1.1"

[dependencies.clippy]
optional = true
version = "~0.0.86"
